[project]
name = 'pixel-legends-core'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.pixel-legends-core_clar]
path = 'contracts/pixel-legends-core_clar.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
